### ISSUE TITLE
Delayed method calls blow up when the last argument is a hash

### ISSUE THREAD

**Issue by javawizard** [instructure/inst-jobs#11]
Minimal reproducible example:

```
module Foo
  def bar(thing)
    puts "yo I was called with: #{thing}"
  end
end

Foo.delay.bar({ yo: 'sup' }) # execution of this job blows up with #<ArgumentError: unknown keywords: :yo>
```

inst-jobs thinks `{ yo: 'sup' }` should be kwargs and [duly calls](https://github.com/instructure/inst-jobs/blob/65dfd66235687383ae447c98136e22cb3a5e7e20/lib/delayed/performable_method.rb#L42) `Foo.bar` as `Foo.bar(**{ yo: 'sup' })`, which blows up.

I'll get around to troubleshooting this at some point, but if y'all know off the top of your head what to fix to get `delay.whatever(...)` to correctly understand whether it's being passed kwargs that'd be just peachy.

**Comment by javawizard** [comment]
Also, would y'all be open to a PR that adds an option to let `Delayed::Testing.drain` raise an exception if any of the drained jobs fail? This took an annoyingly long time to track down because the job failure was silently swallowed in specs.

**Comment by ccutrer** [comment]
I invite you to explore ruby2_keywords, and also try your example with different versions of ruby. Tl;dr: there’s not a simple answer, and I’m not sure there IS an answer even with ruby2_keywords until ruby 3.

**Comment by ccutrer** [comment]
> Also, would y'all be open to a PR that adds an option to let `Delayed::Testing.drain` raise an exception if any of the drained jobs fail? This took an annoyingly long time to track down because the job failure was silently swallowed in specs.

Sure.
