### ISSUE TITLE
support the newer `.delay(queue_args).method(args)` syntax from delayed_job

### ISSUE THREAD

**Issue by codekitchen** [instructure/inst-jobs#6]
https://github.com/collectiveidea/delayed_job/tree/v4.1.1#queuing-jobs

I much prefer this to `send_later` and especially `send_later_enqueue_args`.

**Comment by ccutrer** [comment]
:+1: 

now if only Canvas could get rid of send_later_if_production, and especially send_later_if_some_obscure_condition

Ideally we could not rely on any methods added to Object, though :(
