### ISSUE TITLE
stale args on overwritten `send_later_enqueue_args` job

### ISSUE THREAD

**Issue by jneander** [instructure/inst-jobs#8]
When enqueuing a job with args and the same job already exists, overwriting on conflict updates the job, but not the args passed to it.

```
self.send_later_enqueue_args(:do_thing, {
  :run_at => run_at_date,
  :on_conflict => :overwrite,
  :singleton => Shard.birth.activate { "thing_doer" }
}, args_and_stuff)
```

If this were run again with a different `run_at_date` and different `args_and_stuff`, the date would be changed on the job, but `args_and_stuff` would remain the original value.

**Comment by maneframe** [comment]
I think usually we expect the same args to be used if we're using a singleton but the more I think about it I can't come up with a compelling reason myself why we _shouldn't_ update it...

It'd be pretty straightforward - just add something like `job.handler = new_job.handler if on_conflict == :overwrite` to https://github.com/instructure/inst-jobs/blob/master/lib/delayed/backend/active_record.rb#L382

**Comment by ccutrer** [comment]
Yup, in the case that args differ with each invocation, I would expect `on_conflict: :overwrite` to overwrite both the handler and the run_at. So.. PRs accepted (or Gerrit reviews), and we'll get it through quick

**Comment by ccutrer** [comment]
this was done in https://github.com/instructure/inst-jobs/commit/694c960d61a8657ae3873f2bb6586017241efeef
